from tests.resource_retention_finalization_cases import (
    test_requested_owned_cleanup_failure_keeps_failed_migration_exit_one as test_requested_owned_cleanup_failure_keeps_failed_migration_exit_one,
    test_requested_owned_cleanup_failure_preserves_pass_and_exits_two as test_requested_owned_cleanup_failure_preserves_pass_and_exits_two,
)
from tests.resource_retention_manifest_cases import (
    test_authenticated_manifest_persists_complete_retained_lifecycle as test_authenticated_manifest_persists_complete_retained_lifecycle,
    test_authenticated_ownership_fact_tampering_fails_closed as test_authenticated_ownership_fact_tampering_fails_closed,
    test_retention_manifest_rejects_backend_identity_replacement as test_retention_manifest_rejects_backend_identity_replacement,
)
from tests.resource_retention_policy_cases import (
    test_cleanup_failure_is_persistable_without_losing_policy as test_cleanup_failure_is_persistable_without_losing_policy,
    test_delete_policy_defers_owned_image_removal as test_delete_policy_defers_owned_image_removal,
    test_external_existing_container_is_structurally_retained as test_external_existing_container_is_structurally_retained,
    test_local_continuation_availability_requires_finalization_evidence as test_local_continuation_availability_requires_finalization_evidence,
    test_manifest_setup_failure_preserves_authorized_cleanup as test_manifest_setup_failure_preserves_authorized_cleanup,
    test_owned_delete_finalizer_records_removed_state as test_owned_delete_finalizer_records_removed_state,
    test_retain_finalizer_has_no_delete_side_effect as test_retain_finalizer_has_no_delete_side_effect,
    test_retain_policy_overrides_legacy_image_cleanup as test_retain_policy_overrides_legacy_image_cleanup,
    test_retain_policy_strips_runtime_auto_remove_flag as test_retain_policy_strips_runtime_auto_remove_flag,
    test_task13_forbidden_deletion_remains_retain as test_task13_forbidden_deletion_remains_retain,
)
from tests.resource_retention_security_cases import (
    test_cloned_task13_proof_cannot_authorize_modified_ownership as test_cloned_task13_proof_cannot_authorize_modified_ownership,
    test_retention_finalizer_cannot_self_authorize_deletion as test_retention_finalizer_cannot_self_authorize_deletion,
    test_fabricated_task13_eligibility_cannot_mint_delete_authority as test_fabricated_task13_eligibility_cannot_mint_delete_authority,
    test_owned_image_creation_has_labels_without_runtime_auto_remove as test_owned_image_creation_has_labels_without_runtime_auto_remove,
    test_ownership_token_under_wrong_label_key_prohibits_delete as test_ownership_token_under_wrong_label_key_prohibits_delete,
    test_released_continuation_lock_prohibits_delete_side_effect as test_released_continuation_lock_prohibits_delete_side_effect,
)
