/**
 * python_bind_op.cpp: Optional PyTorch pybind11 binding for an NPU custom operator.
 *
 * This template implements the dual-path execution strategy:
 *   1. ACLNN path (preferred): Uses aclnn{{OP_NAME}}GetWorkspaceSize + aclnn{{OP_NAME}}
 *      - Works when the operator is registered and descriptors match generated ACLNN contracts.
 *      - If this path fails, inspect descriptors, registration, artifacts, and shape support before assuming fallback is valid.
 *
 *   2. ACLRT fallback: Uses aclrtBinaryLoadFromFile + aclrtLaunchKernel
 *      - Directly launches the pre-compiled kernel binary when a direct-launch path is explicitly validated.
 *      - This is not guaranteed to support every shape or tensor layout; it uses the matching .o binary, tiling layout, blockDim rule, and stream policy.
 *      - Binary handle is cached as static. Per-call unload caused segfaults in prior work.
 *
 * Placeholders:
 *   {{MODULE_NAME}}        : Python module name, for example custom_ops_lib
 *   {{OP_NAME}}            : CamelCase operator name
 *   {{op_name}}            : snake_case operator name
 *   {{op_name_lower}}      : lowercase kernel path component
 *   {{CANN_INSTALL_PATH}}  : Active CANN install root
 *   {{VENDOR_NAME}}        : CANN vendor name
 *   {{SOC_VERSION}}        : Target SoC
 *   {{PACKAGE_KERNEL_ROOT}}: Optional adapter-package directory containing op_impl/... resources
 *   {{KERNEL_HASH}}        : Kernel binary hash string
 *   {{TILING_STRUCT}}      : Struct definition for kernel tiling parameters
 *   {{TILING_INIT}}        : Code to initialize the tiling struct from function args
 *   {{OP_INPUTS}}          : Function parameter list, for example "const at::Tensor& a, double scale"
 *   {{OP_RAW_ARGS}}        : raw_args array setup for aclrtLaunchKernel
 *   {{OP_CHECKS}}          : Input validation TORCH_CHECK statements
 */
#include <cctype>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <stdexcept>
#include <string>
#include <vector>

#include <dlfcn.h>
#include <unistd.h>

#include <torch/extension.h>
#include <pybind11/pybind11.h>

#include <acl/acl.h>
#include <acl/acl_rt.h>
#include <torch_npu/csrc/core/npu/NPUStream.h>

#include "pytorch_npu_helper.hpp"

// ============================================================================
// ACLNN API declarations (provided by libcust_opapi.so at link time)
// ============================================================================
// These are generated by the CANN operator build system. The signatures follow
// the pattern: aclnn<OpName>GetWorkspaceSize(...inputs, output, &size, &executor)
//              aclnn<OpName>(workspace, size, executor, stream)
extern "C" aclnnStatus aclnn{{OP_NAME}}GetWorkspaceSize(
    // PLACEHOLDER_NOTE: Fill in ACLNN input parameters matching the generated
    // ACLNN header for the current operator package, including output tensors
    // and scalar attributes in the generated order. An unresolved placeholder
    // means this adapter is source scaffolding rather than runtime evidence.
    {{ACLNN_PARAMS}}
    uint64_t* workspaceSize,
    aclOpExecutor** executor);

extern "C" aclnnStatus aclnn{{OP_NAME}}(
    void* workspace,
    uint64_t workspaceSize,
    aclOpExecutor* executor,
    aclrtStream stream);

namespace py = pybind11;

namespace {

// ============================================================================
// Kernel binary path and function name constants
// ============================================================================
// Resolve the direct-launch binary at runtime. Avoid baking a site-specific
// {{CUSTOM_OPP_PATH}} into the extension. Safe default order:
//   1. ASCEND_CUSTOM_OPP_PATH plus k{{OP_NAME}}KernelRelativePath.
//   2. The adapter module directory plus k{{OP_NAME}}KernelRelativePath.
// Unsafe override order, enabled only when {{MODULE_NAME}}_ALLOW_UNSAFE_BINARY_PATH is truthy:
//   3. {{OP_NAME}}_BINARY_PATH points to the exact kernel object.
//   4. {{MODULE_NAME}}_KERNEL_ROOT plus k{{OP_NAME}}KernelRelativePath.
// ACLRT fallback is fail-closed by default. Enable it only after current-op
// validation by setting {{MODULE_NAME}}_ALLOW_VALIDATED_ACLRT_FALLBACK=1.
// Function name has "_0" suffix. This is the entry point index appended by the CANN compiler.
constexpr char k{{OP_NAME}}BinaryPathEnv[] = "{{OP_NAME}}_BINARY_PATH";
constexpr char k{{OP_NAME}}OppPathEnv[] = "ASCEND_CUSTOM_OPP_PATH";
constexpr char k{{OP_NAME}}DefaultOppPathEnv[] = "ASCEND_OPP_PATH";
constexpr char k{{OP_NAME}}PackageRootEnv[] = "{{MODULE_NAME}}_KERNEL_ROOT";
constexpr char k{{OP_NAME}}AllowUnsafeBinaryPathEnv[] = "{{MODULE_NAME}}_ALLOW_UNSAFE_BINARY_PATH";
constexpr char k{{OP_NAME}}AllowAclrtFallbackEnv[] = "{{MODULE_NAME}}_ALLOW_VALIDATED_ACLRT_FALLBACK";
#ifdef _WIN32
constexpr char kPathListSeparator = ';';
#else
constexpr char kPathListSeparator = ':';
#endif
constexpr char k{{OP_NAME}}KernelRelativePath[] =
    "op_impl/ai_core/tbe/kernel/{{SOC_VERSION}}/{{op_name_lower}}/"
    "{{OP_NAME}}_{{KERNEL_HASH}}.o";
constexpr char k{{OP_NAME}}FunctionName[] = "{{OP_NAME}}_{{KERNEL_HASH}}_0";

bool IsReadableFile(const std::string& path)
{
    return !path.empty() && access(path.c_str(), R_OK) == 0;
}

bool EnvFlagIsTruthy(const char* value)
{
    if (value == nullptr) {
        return false;
    }
    std::string normalized(value);
    for (char& ch : normalized) {
        ch = static_cast<char>(std::tolower(static_cast<unsigned char>(ch)));
    }
    return normalized == "1" || normalized == "true" ||
           normalized == "yes" || normalized == "on";
}

std::string JoinPath(const std::string& root, const std::string& relative)
{
    if (root.empty()) {
        return relative;
    }
    if (root.back() == '/') {
        return root + relative;
    }
    return root + "/" + relative;
}

std::vector<std::string> SplitPathList(const char* value)
{
    std::vector<std::string> entries;
    if (value == nullptr || value[0] == '\0') {
        return entries;
    }
    std::string remaining(value);
    std::string::size_type start = 0;
    while (start <= remaining.size()) {
        const std::string::size_type sep = remaining.find(kPathListSeparator, start);
        const std::string item = remaining.substr(start, sep == std::string::npos ? sep : sep - start);
        if (!item.empty()) {
            entries.push_back(item);
        }
        if (sep == std::string::npos) {
            break;
        }
        start = sep + 1;
    }
    return entries;
}

std::string ResolveModuleDirectory()
{
    Dl_info info;
    if (dladdr(reinterpret_cast<void*>(&ResolveModuleDirectory), &info) == 0 ||
        info.dli_fname == nullptr) {
        return std::string();
    }
    std::string module_path(info.dli_fname);
    const std::string::size_type slash = module_path.find_last_of('/');
    if (slash == std::string::npos) {
        return std::string();
    }
    return module_path.substr(0, slash);
}

std::string Resolve{{OP_NAME}}BinaryPath()
{
    for (const std::string& custom_opp_path : SplitPathList(std::getenv(k{{OP_NAME}}OppPathEnv))) {
        const std::string candidate = JoinPath(custom_opp_path, k{{OP_NAME}}KernelRelativePath);
        if (IsReadableFile(candidate)) {
            return candidate;
        }
    }

    for (const std::string& default_opp_root : SplitPathList(std::getenv(k{{OP_NAME}}DefaultOppPathEnv))) {
        const std::string vendor_candidate = JoinPath(
            JoinPath(default_opp_root, "vendors/{{VENDOR_NAME}}"),
            k{{OP_NAME}}KernelRelativePath);
        if (IsReadableFile(vendor_candidate)) {
            return vendor_candidate;
        }
        const std::string nested_vendor_candidate = JoinPath(
            JoinPath(default_opp_root, "opp/vendors/{{VENDOR_NAME}}"),
            k{{OP_NAME}}KernelRelativePath);
        if (IsReadableFile(nested_vendor_candidate)) {
            return nested_vendor_candidate;
        }
    }

    const std::string module_dir = ResolveModuleDirectory();
    if (!module_dir.empty()) {
        const std::string module_candidate = JoinPath(module_dir, k{{OP_NAME}}KernelRelativePath);
        if (IsReadableFile(module_candidate)) {
            return module_candidate;
        }
    }

    const bool allow_unsafe_paths = EnvFlagIsTruthy(std::getenv(k{{OP_NAME}}AllowUnsafeBinaryPathEnv));
    if (allow_unsafe_paths) {
        const char* explicit_path = std::getenv(k{{OP_NAME}}BinaryPathEnv);
        if (explicit_path != nullptr && explicit_path[0] != '\0') {
            return std::string(explicit_path);
        }

        const char* package_root = std::getenv(k{{OP_NAME}}PackageRootEnv);
        if (package_root != nullptr && package_root[0] != '\0') {
            const std::string candidate = JoinPath(package_root, k{{OP_NAME}}KernelRelativePath);
            if (IsReadableFile(candidate)) {
                return candidate;
            }
        }
    }

    throw std::runtime_error(
        "Missing {{OP_NAME}} direct-launch binary. Export ASCEND_CUSTOM_OPP_PATH "
        "or package op_impl resources beside the adapter module. Exact binary/root "
        "environment overrides require {{MODULE_NAME}}_ALLOW_UNSAFE_BINARY_PATH=1.");
}

// ============================================================================
// RAII wrapper for aclTensor handles
// ============================================================================
struct AclTensorHandle {
    explicit AclTensorHandle(const at::Tensor& tensor) : value(ConvertType(tensor)) {}
    ~AclTensorHandle() { Release(value); }
    aclTensor* value;
};

// ============================================================================
// ACL error checking utility
// ============================================================================
void CheckAcl(aclError status, const char* what)
{
    TORCH_CHECK(status == ACL_SUCCESS, what, " failed with aclError=", static_cast<int>(status));
}

// ============================================================================
// Static kernel handle caching
// ============================================================================
// Observed pitfall: Binary and function handles are cached as static variables.
// Per-invocation aclrtBinaryUnload caused use-after-free
// crashes because the function handle becomes invalid after unload.
// The handles persist for the process lifetime (loaded once, never unloaded).
aclrtFuncHandle Get{{OP_NAME}}Function()
{
    static aclrtBinHandle binary_handle = nullptr;
    static aclrtFuncHandle func_handle = nullptr;
    if (func_handle == nullptr) {
        const std::string binary_path = Resolve{{OP_NAME}}BinaryPath();
        CheckAcl(aclrtBinaryLoadFromFile(binary_path.c_str(), nullptr, &binary_handle),
                 "aclrtBinaryLoadFromFile");
        CheckAcl(aclrtBinaryGetFunction(binary_handle, k{{OP_NAME}}FunctionName, &func_handle),
                 "aclrtBinaryGetFunction");
    }
    return func_handle;
}

// ============================================================================
// ACLRT Fallback: Direct kernel launch
// ============================================================================
// This function is called only after the direct-launch path has been validated
// for the current operator signature, tiling layout, blockDim rule, tensor
// layout, and stream ownership. ACLNN failure is a diagnostic signal first; do
// not assume fallback is correct for every status or shape.
at::Tensor Launch{{OP_NAME}}ViaAclrt(
    aclrtStream stream,
    {{OP_INPUTS}})
{
    // Verify the kernel binary exists on disk
    const std::string binary_path = Resolve{{OP_NAME}}BinaryPath();
    TORCH_CHECK(access(binary_path.c_str(), R_OK) == 0,
                 "Missing {{OP_NAME}} fallback binary: ", binary_path);

    // -----------------------------------------------------------------------
    // Dynamic blockDim calculation
    // -----------------------------------------------------------------------
    // blockDim controls how many AI cores execute in parallel. Derive this from
    // the current op's tiling contract and target shapes, then validate it
    // against the direct kernel and framework integration tests.
    uint32_t workload_extent = static_cast<uint32_t>(/* primary workload dimension */);
    uint32_t blockDim = (workload_extent >= 64) ? (workload_extent / 16) : 1;
    if (blockDim > 8) blockDim = 8;

    // Allocate output tensor (same shape/dtype as primary input)
    at::Tensor out = at::zeros_like(/* primary input tensor */);

    // -----------------------------------------------------------------------
    // Tiling data structure
    // -----------------------------------------------------------------------
    // This struct matches the TilingData layout expected by the kernel.
    // static_assert can verify size matches opParaSize in the kernel config.
    // Mismatched sizes cause silent kernel failures or garbage output.
    {{TILING_STRUCT}}
    // Example:
    // struct KernelTilingData {
    //     uint32_t element_count;
    //     uint32_t row_count;
    //     uint32_t column_count;
    //     uint32_t flags;
    // };
    // static_assert(sizeof(KernelTilingData) == {{OP_PARA_SIZE}}, "Match opParaSize");

    // Initialize tiling parameters from function arguments
    {{TILING_INIT}}
    // Example:
    // KernelTilingData tiling {
    //     static_cast<uint32_t>(/* total elements */),
    //     static_cast<uint32_t>(/* rows */),
    //     static_cast<uint32_t>(/* columns */),
    //     static_cast<uint32_t>(/* flags */),
    // };

    // Get cached function handle (loaded once, never unloaded)
    aclrtFuncHandle func_handle = Get{{OP_NAME}}Function();

    // -----------------------------------------------------------------------
    // raw_args array for aclrtLaunchKernel
    // -----------------------------------------------------------------------
    // Layout: [input_ptrs..., output_ptr, workspace_ptr (nullptr if unused), &tiling]
    // The last element is a pointer to the tiling struct.
    // workspace_ptr is nullptr unless your kernel uses extra workspace memory.
    {{OP_RAW_ARGS}}
    // Example:
    // void* raw_args[6];
    // raw_args[0] = input_a.data_ptr();
    // raw_args[1] = input_b.data_ptr();
    // raw_args[2] = input_c.data_ptr();
    // raw_args[3] = out.data_ptr();
    // raw_args[4] = nullptr;       // workspace (unused)
    // raw_args[5] = &tiling;       // tiling data (last)

    // Launch the kernel on the NPU stream
    CheckAcl(aclrtLaunchKernel(func_handle, blockDim, raw_args, sizeof(raw_args), stream),
             "aclrtLaunchKernel");

    return out;
}

}  // namespace

// ============================================================================
// Main operator function: ACLNN path with ACLRT fallback
// ============================================================================
static at::Tensor {{op_name}}_npu(
    {{OP_INPUTS}})
{
    // -----------------------------------------------------------------------
    // Input validation
    // -----------------------------------------------------------------------
    {{OP_CHECKS}}
    // Example checks:
    // TORCH_CHECK(input.device().is_privateuseone(), "{{op_name}} expects NPU tensors");
    // TORCH_CHECK(input.dim() == 2, "input expected 2D");
    // TORCH_CHECK(input.scalar_type() == at::kFloat, "input expected float32");

    // Guard ensures all allocations happen on the correct device
    at::DeviceGuard guard(/* primary input */.device());

    // Allocate output tensor
    at::Tensor out = at::zeros_like(/* primary input */);

    // Resolve the current NPU stream once and use it for ACLNN and any fallback
    // launch so both paths follow the same stream ownership rule.
    aclrtStream stream = c10_npu::getCurrentNPUStream(
        /* primary input */.device().index()).stream();

    // -----------------------------------------------------------------------
    // Convert PyTorch tensors to ACL tensor handles (RAII)
    // -----------------------------------------------------------------------
    // AclTensorHandle wraps ConvertType() and auto-releases on scope exit.
    // PLACEHOLDER_NOTE: Create AclTensorHandle for each tensor input.
    // Unresolved adapter placeholders are source scaffolding rather than runtime
    // or benchmark evidence.
    // Example:
    // AclTensorHandle acl_input(input);
    // TORCH_CHECK(acl_input.value != nullptr, "ConvertType failed for input");

    // -----------------------------------------------------------------------
    // Step 1: Try ACLNN path (preferred, graph-compiled execution)
    // -----------------------------------------------------------------------
    // aclnn<Op>GetWorkspaceSize compiles an execution graph and returns the
    // workspace size. If it fails (status != 0), direct launch may be
    // tried only after the current op has a validated ACLRT path.
    //
    // Common failure: error 161001 means ACLNN phase-1 validation failed. Check
    // tensor descriptors, generated signatures, custom OPP resource registration,
    // and installed artifact identity before deciding whether direct launch is
    // valid for this call.
    //
    // For multi-op generated ACLNN packages, keep executor state per generated
    // wrapper/op signature. If later ops fail after the first op succeeds,
    // verify that all package binary resources were registered before the first
    // executor space was created; sharing one executor space
    // across different op signatures.
    uint64_t workspace_size = 0;
    aclOpExecutor* executor = nullptr;

    aclnnStatus status = aclnn{{OP_NAME}}GetWorkspaceSize(
        // PLACEHOLDER_NOTE: Pass ACL tensor handles and scalar params here.
        // Leaving this unresolved means the ACLNN route is incomplete and cannot
        // satisfy adapter, coverage, benchmark, or full migration evidence.
        // Example: acl_input.value, scale, flags, acl_out.value,
        &workspace_size,
        &executor);

    // -----------------------------------------------------------------------
    // Step 2: If ACLNN fails, optionally use validated ACLRT direct launch
    // -----------------------------------------------------------------------
    if (status != 0) {
        // ACLNN path failed. Fail closed unless this op has a validated ACLRT path
        // for the current status, shape, layout, tiling, stream, and mixed-op sequence.
        TORCH_CHECK(EnvFlagIsTruthy(std::getenv(k{{OP_NAME}}AllowAclrtFallbackEnv)),
                    "aclnn{{OP_NAME}}GetWorkspaceSize failed: ", static_cast<int>(status),
                    "; unvalidated ACLRT direct-launch fallback is disabled. Fix generated ",
                    "descriptors/artifacts or set {{MODULE_NAME}}_ALLOW_VALIDATED_ACLRT_FALLBACK=1 ",
                    "only after recording per-op direct-launch validation evidence.");
        return Launch{{OP_NAME}}ViaAclrt(stream, /* pass original function args */);
    }
    TORCH_CHECK(executor != nullptr, "aclnn{{OP_NAME}}GetWorkspaceSize returned null executor");

    // -----------------------------------------------------------------------
    // Step 3: Allocate workspace and execute via ACLNN
    // -----------------------------------------------------------------------
    at::Tensor workspace;
    void* workspace_ptr = nullptr;
    if (workspace_size > 0) {
        workspace = at::empty({static_cast<int64_t>(workspace_size)},
                              /* primary input */.options().dtype(at::kByte));
        workspace_ptr = const_cast<void*>(workspace.storage().data());
    }

    status = aclnn{{OP_NAME}}(workspace_ptr, workspace_size, executor, stream);
    TORCH_CHECK(status == 0, "aclnn{{OP_NAME}} failed: ", static_cast<int>(status));
    return out;
}

// ============================================================================
// Pybind11 module definition
// ============================================================================
PYBIND11_MODULE({{MODULE_NAME}}, m)
{
    // Optional benchmark metadata. Projects can expose equivalent
    // metadata under their own adapter API when pybind attributes are not used.
    m.attr("USES_GENERATED_ACLNN") = true;
    m.attr("CUSTOM_OPP_VENDOR") = "{{VENDOR_NAME}}";

    m.def("{{op_name}}", &{{op_name}}_npu,
          // PLACEHOLDER_NOTE: Add py::arg() for each parameter in the adapter API.
          // Missing argument bindings mean this adapter is not a callable manifest
          // entry and cannot count as custom-op replacement.
          // Example:
          // py::arg("input"), py::arg("scale"), py::arg("flags") = 0
          "{{OP_NAME}} operator on NPU (ACLNN path with validated ACLRT direct-launch fallback)");
}
